import { CatalogItem } from "../models";

export const dummyCatalogData: CatalogItem[] = [
  {
    id: "cat-001",
    code: "DEV-101",
    name: "Frontend Development",
    description: "JavaScript/TypeScript development with React or similar frameworks",
    defaultUnit: "hours",
    defaultPrice: 95,
    category: "DEV",
    type: "service",
    taxRate: 20,
    isActive: true,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01")
  },
  {
    id: "cat-002",
    code: "DEV-102",
    name: "Backend Development",
    description: "Node.js/Express/NestJS development for APIs and server applications",
    defaultUnit: "hours",
    defaultPrice: 110,
    category: "DEV",
    type: "service",
    taxRate: 20,
    isActive: true,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01")
  },
  {
    id: "cat-003",
    code: "DES-101",
    name: "UI/UX Design",
    description: "User interface and user experience design",
    defaultUnit: "hours",
    defaultPrice: 90,
    category: "DES",
    type: "service",
    taxRate: 20,
    isActive: true,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01")
  },
  {
    id: "cat-004",
    code: "DES-201",
    name: "Logo Design",
    description: "Professional logo design including multiple concepts and revisions",
    defaultUnit: "pcs",
    defaultPrice: 1200,
    category: "DES",
    type: "service",
    taxRate: 20,
    isActive: true,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01")
  },
  {
    id: "cat-005",
    code: "CON-215",
    name: "Business Strategy Consulting",
    description: "Business strategy development and optimization consulting",
    defaultUnit: "hours",
    defaultPrice: 200,
    category: "CON",
    type: "service",
    taxRate: 20,
    isActive: true,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01")
  },
  {
    id: "cat-006",
    code: "SRV-100",
    name: "Server Maintenance",
    description: "Regular server maintenance, updates and monitoring",
    defaultUnit: "month",
    defaultPrice: 500,
    category: "SRV",
    type: "service",
    taxRate: 20,
    isActive: true,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01")
  },
  {
    id: "cat-007",
    code: "SUP-300",
    name: "Premium Support Package",
    description: "24/7 priority support with guaranteed response times",
    defaultUnit: "month",
    defaultPrice: 800,
    category: "SUP",
    type: "service",
    taxRate: 20,
    isActive: true,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01")
  },
  {
    id: "cat-008",
    code: "HW-405",
    name: "Server Hardware - Dell R640",
    description: "Dell PowerEdge R640 Server with standard configuration",
    defaultUnit: "pcs",
    defaultPrice: 3200,
    category: "HW",
    type: "product",
    taxRate: 20,
    isActive: true,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01")
  },
  {
    id: "cat-009",
    code: "SW-512",
    name: "CRM Software License",
    description: "Enterprise CRM software license - annual subscription",
    defaultUnit: "users",
    defaultPrice: 120,
    category: "SW",
    type: "product",
    taxRate: 20,
    isActive: true,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01")
  },
  {
    id: "cat-010",
    code: "SEC-350",
    name: "Security Audit",
    description: "Comprehensive security audit and vulnerability assessment",
    defaultUnit: "pcs",
    defaultPrice: 1200,
    category: "SEC",
    type: "service",
    taxRate: 20,
    isActive: true,
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01")
  }
];