import React from 'react';
import { View, Text } from '@react-pdf/renderer';
import { invoiceStyles } from '../styles/InvoiceStyles';
import { CompanySettings } from '@/lib/models';

interface InvoiceFooterProps {
  notes?: string;
  companyInfo: CompanySettings;
}

export const InvoiceFooter: React.FC<InvoiceFooterProps> = ({ 
  notes,
  companyInfo
}) => {
  // Get company info (with fallbacks)
  const companyName = companyInfo?.name || 'ChaDev';
  
  // Static values for fields not in CompanySettings
  const bankName = 'Migros Bank AG';
  const accountName = companyName;
  const accountNumber = '1234567890';
  const iban = 'CH78 0840 1000 0724 3366 3';
  const bic = 'MIGRCHZZXXX';
  const terms = 'Payment is due within 14 days of receipt. Late payments are subject to a 2% monthly fee.';
  const footerText = 'Generated by InvoicePro - Smart Invoicing Solution';
  
  return (
    <View style={invoiceStyles.footer}>
      <View style={invoiceStyles.footerSection}>
        <Text style={invoiceStyles.footerSectionTitle}>Notes</Text>
        <Text style={invoiceStyles.footerText}>{notes || 'Monthly IT services package.'}</Text>
      </View>
      
      <View style={invoiceStyles.footerSection}>
        <Text style={invoiceStyles.footerSectionTitle}>Payment Information</Text>
        <Text style={invoiceStyles.footerText}>Please transfer the amount to:</Text>
        <Text style={invoiceStyles.footerText}>Bank: {bankName}</Text>
        <Text style={invoiceStyles.footerText}>Account Name: {accountName}</Text>
        <Text style={invoiceStyles.footerText}>Account Number: {accountNumber}</Text>
        <Text style={invoiceStyles.footerText}>IBAN: {iban}</Text>
        <Text style={invoiceStyles.footerText}>BIC: {bic}</Text>
      </View>
      
      <View style={invoiceStyles.footerSection}>
        <Text style={invoiceStyles.footerSectionTitle}>Terms & Conditions</Text>
        <Text style={invoiceStyles.footerText}>{terms}</Text>
      </View>
      
      <View style={invoiceStyles.thankYouSection}>
        <Text style={invoiceStyles.thankYouText}>Thank you for your business!</Text>
        <Text style={invoiceStyles.poweredByText}>{footerText}</Text>
      </View>
    </View>
  );
};